name: Kustomize Setup
description: 'Setup a Kustomize environment and add it to the path'
author: philiplehmann
branding:
  icon: download
  color: blue
inputs:
  kustomize-version:
    description: 'Version Spec of the version to use.  Examples: 5.x, 5.4.2, >=5.4.0'
    required: false
    default: '*'
  github-token:
    description: 'Token for the repository. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`.'
    required: false
    default: ${{ github.token }}
  fail-fast:
    description: 'Fail quickly on github rate limit. "false" or "true".'
    required: false
    default: 'true'
runs:
  using: 'node20'
  main: 'dist/index.js'
